### ISSUE TITLE
No proofs and no coins

### ISSUE THREAD

**Issue by jmz-bit** [bpx-network/bpx-blockchain#2]
I'm farming this for a few hours now. My ETW is a few minutes. But no proof found and no rewards.

My current Hight is 241.

Any explanation of this ?

**Comment by MinesofMoriaCrypto** [comment]
I apologize for doing this... but not sure where else to ask since this is so new. Got any full nodes you can share?

**Comment by bpx-network** [comment]
Hi,
Our blockchain has just taken off and the ETW you see is very far from the real value.
Blockchain works correct, proofs are generated and rewards are granted but it takes a long time.
We have to wait for netspace to reach at least a few hundred PB.

**Comment by bpx-network** [comment]
@MinesofMoriaCrypto if you have sync issues try to connect manually to following addresses:

introducer.bpxcoin.cc:27912
node.bpxcoin.cc:27911

Here is a list of example full nodes:

89.151.37.30
87.184.220.61
128.106.250.223
128.106.250.223
185.21.220.2
83.103.246.158
96.3.84.174
93.192.224.142
37.201.225.205
180.75.236.54
73.147.146.172
168.235.173.26
88.101.182.47
1.65.143.219
212.21.16.224
185.53.22.15
90.182.197.54
79.198.189.159
79.112.16.79
62.133.129.141
95.107.38.134
108.173.74.74
66.252.197.9
122.117.194.138
84.10.160.160
195.213.171.156
24.66.104.84
185.128.216.163
94.14.143.239
88.230.18.210
46.205.240.163
71.57.134.135
5.173.121.120
84.175.39.72
181.215.176.11
86.137.25.169
93.91.157.22
97.92.69.144
192.75.158.166
58.7.215.95
93.175.75.185
185.118.167.151
91.86.50.213
80.81.15.25
27.71.106.231
194.63.128.244
193.122.96.188
217.138.227.150
171.221.70.252
79.122.193.207
173.170.40.7
