### ISSUE TITLE
Cannot Connect To Peers

### ISSUE THREAD

**Issue by MinesofMoriaCrypto** [bpx-network/bpx-blockchain#4]
When entering a peer, port 27911, the following error is produced:

"Error
Start client failed, or server is not set"

I reinstalled twice, having deleted all directories and config, including properly deleting directories in /user/ & /user/appdata/

EDIT:
Introducer works on port 27912
node.bpxcoin.cc works on 27911

But no peers of the list developer provided will connect, all report same error.

Windows 10
BPX 1.0.0

**Comment by bpx-network** [comment]
Please upload full debug.log

**Comment by MinesofMoriaCrypto** [comment]
[debug.log](https://github.com/bpx-network/bpx-blockchain/files/8021280/debug.log)
